### ISSUE TITLE
Tell me more about this...

### ISSUE THREAD

**Issue by cdubz** [nicholaswilde/docker-babybuddy#18]
Hi @nicholaswilde :wave: -- I'm curious to know more about why you created this implementation. I'm not terribly familiar with Docker so Baby Buddy's implementation has always been somewhat haphazard. If what you have going here is a better general purpose approach I'd love to make it the "official" Baby Buddy for Docker path. Please let me know your thoughts.

FTR this repo was pointed out to me in babybuddy/babybuddy#199.

**Comment by nicholaswilde** [comment]
Hey! Thanks for reaching out! 🙏🏽 I started this repo because I wanted to host a multi-architecture image (`amd64`, `arm64`, & `armv7`) for BB to use in a [helm chart](https://artifacthub.io/packages/helm/nicholaswilde/babybuddy) and your image was only offered in `amd64`.  Yes, I could have requested that you offer the image in all three architectures, but I like the challenge of hosting it myself.

In terms of the official image, I don't think that I have enough experience nor the confidence, to offer it. I appreciate the offer, though! Perhaps you can reach out to [LinuxServer.io](https://www.linuxserver.io/) (LSIO) to see if they'll host it? They seem to have a lot more experience and I've seen a few apps that point to LSIO as being the official image.

**Comment by cdubz** [comment]
Well "official" isn't really the right word, hah -- I just mean I'd like for Baby Buddy's automated and documented Docker support to cover as many use cases as possible. I didn't realize ARM support was so limited. LSIO does look really cool though. I'm going to look in to that more as well. Thanks for the reference!

**Comment by nicholaswilde** [comment]
No problem!

**Comment by cdubz** [comment]
LSIO folks were super helpful! They've got a first release up that I'll be testing soon and updating documentation for. Thanks again for the ref.

https://github.com/linuxserver/docker-babybuddy

**Comment by nicholaswilde** [comment]
Excellent! I'm glad that they were helpful.

@milkplus27 Would you mind trying LSIO's image to see if it fixes #19?

**Comment by nicholaswilde** [comment]
I'll probably end up deprecating/archiving this repo and point to the LSIO version.
